include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for EdgePulse
LUCI_DEPENDS:=+edgepulse +luci-base +rpcd
LUCI_PKGARCH:=all

PKG_LICENSE:=MIT
PKG_MAINTAINER:=edgepulse-labs

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

