#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

service_triggers()
{
	procd_add_reload_trigger "edgepulse"
}

start_service()
{
	local enabled interval

	config_load edgepulse
	config_get_bool enabled main enabled 1
	[ "$enabled" -eq 1 ] || return 0

	config_get interval main sample_interval_sec 5

	procd_open_instance
	procd_set_param command /usr/bin/edgepulse daemon "$interval"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service()
{
	stop
	start
}
