#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

PROG=/usr/sbin/edgepulse

start_service() {
	local enabled

	config_load edgepulse
	config_get_bool enabled main enabled 0

	[ "$enabled" -eq 1 ] || return 0
	[ -x "$PROG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG" daemon
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	stop
	start
}

